apply_for_role.settings:
  type: config_object
  label: 'Apply for Role configuration'
  mapping:
    multiple_roles_per_app:
      type: boolean
      label: 'Allow a user to select multiple roles on application form.'

    #Not boolean because choices are either no(0), optional(1) or yes(2)
    apply_for_role_on_registration_form:
    #boolean?
      type: integer
      label: 'Placement of apply for role on registration form.'

    # @TODO: Determine just what this does and update label if incorrect.
    display_approved_roles_app_form:
      type: boolean
      label: 'Displaying of the approved roles app form'

    allow_user_message_with_app:
      type: boolean
      label: 'Allow the user to submit a message with their application.'

    #figure out how to store multiple roles? See OS training!
    apply_for_role_roles:
      type: sequence
      label: 'List of roles that a user can apply for with apply for role.'

    user_apply_form_description:
      type: string
      label: 'User application form description field.'

    send_email_to_admin:
      type: boolean
      label: 'Send an email to the admin(s) on role application.'

    admin_email_addresses:
      type: string
      label: 'comma seperated list of emails -OR- blank to send to UID 1'

    admin_email_subject:
      type: string
      label: 'Subject of email going to administrator(s)'

    admin_email_body:
      type: string
      label: 'Body of email going to administrator(s)'

    send_user_approval_email:
      type: boolean
      label: 'Send an email to the user upon role application approval.'

    send_user_approval_subject:
      type: string
      label: 'Subject line of email to users upon role application approval'

    send_user_approval_body:
      type: string
      label: 'body of email to users upon role application approval'

    send_user_deny_email:
      type: boolean
      label: 'Send users a denial email if application is denied.'

    send_user_deny_subject:
      type: string
      label: 'User application denial email subject line.'

    send_user_deny_body:
      type: string
      label: 'User application denial email body.'
