condition.plugin.message_type:
  type: condition.plugin
  mapping:
    message_types:
      type: sequence
      label: 'Allowed message types'
      sequence:
        type: string
        label: 'Message type'
