<?php

/**
 * @file
 * Contains appointment_edu.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function appointment_edu_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the appointment_edu module.
    case 'help.page.appointment_edu':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Appointment Module For EDu System.') . '</p>';
      return $output;

    default:
  }
}

function appointment_edu_theme() {
  // We use a template file to allow for translation of blocks of content.
  // Therefore we need to add this content at the theming layer.
  return [
    'appointment_edu_description' => [
      'template' => 'description',
      'variables' => [],
    ],
  ];
}
